import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarHeader,
  SidebarMenu,
  SidebarProvider,
  SidebarTrigger,
  useSidebar
} from "@/components/ui/sidebar"
import { Button } from "@/components/ui/button";
import Link from "next/link"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <SidebarProvider>
      <Sidebar collapsible="offcanvas">
        <SidebarHeader />
        <SidebarContent>
          <SidebarMenu className="px-2">
            <Button asChild variant="default" className="mx-4">
              <Link href="/media/create">New media</Link>
            </Button>
          </SidebarMenu>
        </SidebarContent>
        <SidebarFooter />
      </Sidebar>
      <SidebarTrigger/>
        {children}
    </SidebarProvider>
      </body>
    </html>
  );
}
